# Generated by Django 4.2.4 on 2023-09-02 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0046_alter_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('date_of_end', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.student')),
            ],
        ),
    ]
