# Generated by Django 4.2.4 on 2023-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_coursepurchase_date_of_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepurchase',
            name='date_of_join',
            field=models.DateField(auto_now_add=True),
        ),
    ]
