# Generated by Django 4.2.4 on 2023-09-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0073_alter_course_duration'),
        ('Student', '0003_alter_coursepurchase_date_of_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.teacher')),
            ],
        ),
    ]
