# Generated by Django 4.2.4 on 2023-09-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_of_end',
            field=models.DateField(null=True),
        ),
    ]
