# Generated by Django 4.2.4 on 2023-08-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentmark',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='custumuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='custumuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='note',
            name='course',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='test',
        ),
        migrations.RemoveField(
            model_name='student',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
        migrations.RemoveField(
            model_name='test',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testmark',
            name='test',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='course',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentMark',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CustumUser',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestMark',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
