# Generated by Django 4.2.4 on 2023-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_custumuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custumuser',
            name='teacher_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(null=True, related_name='students', to='Manager.student'),
        ),
    ]
