# Generated by Django 4.2.4 on 2023-08-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_remove_custumuser_teacher_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(null=True, related_name='courses', to='Manager.student'),
        ),
    ]
