# Generated by Django 4.2.4 on 2023-08-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Manager', '0007_alter_course_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustumUser',
            new_name='CustomUser',
        ),
    ]
