# Generated by Django 4.2.4 on 2023-08-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0009_customuser_is_manager_customuser_is_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager_status',
            field=models.BooleanField(default=False),
        ),
    ]
