# Generated by Django 4.2.4 on 2023-08-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0010_customuser_manager_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
