# Generated by Django 4.2.4 on 2023-08-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0011_remove_customuser_manager_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
