# Generated by Django 4.2.4 on 2023-08-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0014_remove_course_student_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Mobile No'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Designation',
            field=models.CharField(max_length=200, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Qualification',
            field=models.CharField(choices=[('SSLC', 'SSLC'), ('Higher Secondary', 'Higher Secondary'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Post Graduate', 'Post Graduate'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], max_length=100, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(max_length=100, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
