# Generated by Django 4.2.4 on 2023-08-29 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0015_course_status_teacher_email_teacher_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
