# Generated by Django 4.2.4 on 2023-08-29 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0016_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
