# Generated by Django 4.2.4 on 2023-08-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0018_rename_designation_teacher_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
