# Generated by Django 4.2.4 on 2023-08-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0019_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
    ]
