# Generated by Django 4.2.4 on 2023-08-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0020_remove_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
