# Generated by Django 4.2.4 on 2023-08-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0021_teacher_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
