# Generated by Django 4.2.4 on 2023-08-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0022_alter_teacher_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(upload_to='profile_images', verbose_name='Poster file upload'),
        ),
    ]
