# Generated by Django 4.2.4 on 2023-08-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0024_teacher_is_suspend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video', models.FileField(upload_to='content_videos')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
