# Generated by Django 4.2.4 on 2023-08-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0026_alter_content_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('doc', models.FileField(upload_to='doc_files')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
