# Generated by Django 4.2.4 on 2023-08-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0027_documentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('venue', models.CharField(max_length=300)),
            ],
        ),
    ]
