# Generated by Django 4.2.4 on 2023-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0028_eventcalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcalender',
            name='link',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='eventcalender',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
