# Generated by Django 4.2.4 on 2023-08-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0029_eventcalender_link_alter_eventcalender_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcalender',
            name='link',
        ),
        migrations.AddField(
            model_name='eventcalender',
            name='is_zoom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventcalender',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='eventcalender',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
