# Generated by Django 4.2.4 on 2023-08-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0030_remove_eventcalender_link_eventcalender_is_zoom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcalender',
            name='venue',
        ),
    ]
