# Generated by Django 4.2.4 on 2023-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0033_questanswer_datetime_alter_questanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questanswer',
            name='answer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
