# Generated by Django 4.2.4 on 2023-09-01 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0034_alter_questanswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Qualification',
            new_name='qualification',
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
