# Generated by Django 4.2.4 on 2023-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0035_rename_qualification_student_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
