# Generated by Django 4.2.4 on 2023-09-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0037_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
