# Generated by Django 4.2.4 on 2023-09-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0040_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
