# Generated by Django 4.2.4 on 2023-09-01 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0043_remove_assignmentmark_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('qualification', models.CharField(choices=[('SSLC', 'SSLC'), ('Higher Secondary', 'Higher Secondary'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Post Graduate', 'Post Graduate'), ('Other', 'Other')], max_length=100)),
                ('phone_no', models.IntegerField(null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
