# Generated by Django 4.2.4 on 2023-09-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0044_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.FileField(null=True, upload_to='course_posters'),
        ),
    ]
