# Generated by Django 4.2.4 on 2023-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0047_remove_assignment_deadline_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
