# Generated by Django 4.2.4 on 2023-09-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0051_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='name',
        ),
    ]
