# Generated by Django 4.2.4 on 2023-09-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0053_rename_total_mark_test_no_quesions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='no_quesions',
        ),
        migrations.AddField(
            model_name='test',
            name='no_questions',
            field=models.IntegerField(null=True),
        ),
    ]
