# Generated by Django 4.2.4 on 2023-09-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0054_remove_test_no_quesions_test_no_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='A',
            new_name='optionA',
        ),
        migrations.AlterField(
            model_name='questions',
            name='B',
            field=models.CharField(default='option B', max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='C',
            field=models.CharField(default='option C', max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='D',
            field=models.CharField(default='option D', max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(choices=[(models.CharField(default='option A', max_length=300), 'A'), (models.CharField(default='option B', max_length=300), 'B'), (models.CharField(default='option C', max_length=300), 'C'), (models.CharField(default='option D', max_length=300), 'D')], max_length=100),
        ),
    ]
