# Generated by Django 4.2.4 on 2023-09-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0055_rename_a_questions_optiona_alter_questions_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='optionA',
            new_name='A',
        ),
    ]
