# Generated by Django 4.2.4 on 2023-09-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0056_rename_optiona_questions_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='A',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(choices=[(models.CharField(max_length=300), 'A'), (models.CharField(default='option B', max_length=300), 'B'), (models.CharField(default='option C', max_length=300), 'C'), (models.CharField(default='option D', max_length=300), 'D')], max_length=100),
        ),
    ]
