# Generated by Django 4.2.4 on 2023-09-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0060_alter_questions_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='tutorial',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
