# Generated by Django 4.2.4 on 2023-09-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0061_remove_test_tutorial_delete_questions_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('no_questions', models.IntegerField(null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('A', models.CharField(max_length=300)),
                ('B', models.CharField(max_length=300)),
                ('C', models.CharField(max_length=300)),
                ('D', models.CharField(max_length=300)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=300)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.test')),
            ],
        ),
    ]
