# Generated by Django 4.2.4 on 2023-09-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0063_test_is_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(upload_to='profile_images', verbose_name='profile pic upload'),
        ),
        migrations.DeleteModel(
            name='AssignmentMark',
        ),
    ]
