# Generated by Django 4.2.4 on 2023-09-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0064_alter_teacher_profile_delete_assignmentmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.student')),
            ],
        ),
    ]
