# Generated by Django 4.2.4 on 2023-09-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0067_assignmentfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentFile',
        ),
    ]
