# Generated by Django 4.2.4 on 2023-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0069_assignmentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfile',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
