# Generated by Django 4.2.4 on 2023-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0070_alter_assignmentfile_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMark',
        ),
        migrations.RemoveField(
            model_name='test',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='assignmentfile',
            name='ass_file',
            field=models.FileField(upload_to='assignment_pdf', verbose_name='Upload Assignment File'),
        ),
        migrations.AlterField(
            model_name='assignmentfile',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
