# Generated by Django 4.2.4 on 2023-09-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0072_testmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[(3, 3), (3, 6), (3, 9), (3, 12)]),
        ),
    ]
