# Generated by Django 4.2.4 on 2023-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0073_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='student_profile'),
        ),
    ]
